### ISSUE TITLE
parallel

### ISSUE THREAD

**Issue by apprahuman** [dwisiswant0/awesome-oneliner-bugbounty#44]
where I can find parallel and what its does actually

**Comment by santhoshvr** [comment]
Can you elaborate your question please ?
Your Question is very too short to understand 🙄

**Comment by apprahuman** [comment]
Under Open-redirect by @N3T_hunt3r
cat URLS.txt | gf url | tee url-redirect.txt && cat url-redirect.txt | parallel -j 10 curl --proxy http://127.0.0.1:8080 -sk > /dev/null

what is the correct GitHub repo for parallel, what does this parallel do.. sends HTTP requests??

**Comment by ramsy0dev** [comment]
@apprahuman `parallel` allows you to parallelize the execution of shell commands. This utility is not a standard part of most Linux distributions, so you may need to install it.

* for Debian based linux systems:

```bash
sudo apt-get install parallel
```

* On arch:

```bash
sudo pacman -S parallel
```

* On a Red Hat-based system like CentOS or Fedora, you can use:

```bash
sudo yum install parallel
```

Alternatively, you can download and install it from the official website: https://www.gnu.org/software/parallel/

**Comment by apprahuman** [comment]
@ramsy0dev Thanks for the explanation 🫡
